---

- hosts: all

  # pre_tasks:
  # - name: Update apt cache if needed.
  #   apt: 
  #     update_cache: yes
  #     cache_valid_time: 3600

  tasks:

  - name: Ensure Chocolatey is installed.
    win_chocolatey:
      name: chocolatey
    
  - name: Install pGina
    win_chocolatey:
      name:
      - pgina
      state: present

  - name: Encrypt LDAP password for nGina.
    ansible.windows.win_powershell:
      script: |
        Install-PackageProvider -Name NuGet | Out-Null
        Register-PackageSource -Name NuGet -Location https://www.nuget.org/api/v2 -ProviderName NuGet | Out-Null
        Install-Package -Name System.Security.Cryptography.ProtectedData -ProviderName NuGet -Scope CurrentUser -RequiredVersion 7.0.0 -SkipDependencies -Destination . -Force -Source NuGet | Out-Null
        Move-Item ".\System.Security.Cryptography.ProtectedData.7.0.0\lib\net462\System.Security.Cryptography.ProtectedData.dll" "C:\Users\vagrant\System.Security.Cryptography.ProtectedData.dll" | Out-Null

        $assemblies=(
            "System",
            "System.Runtime",
            "System.Security",
            "System.Security.Cryptography.ProtectedData"
        )

        $source=@"
        using System;
        using System.Text;
        using System.Security.Cryptography;

        namespace pGina {
            public static class Helper {
                public static string Encrypt(string value){
                    return Convert.ToBase64String(ProtectedData.Protect(Encoding.UTF8.GetBytes(value), null, DataProtectionScope.LocalMachine));
                }
            }
        }
        "@

        Add-Type -ReferencedAssemblies $assemblies -TypeDefinition $source -Language CSharp | Out-Null
        [pGina.Helper]::Encrypt("password")
      arguments:
      - -ExecutionPolicy
      - ByPass
    register: nGinaPassword

  - name: Configure pGina - Enable LDAP plugin to authenticate
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\pGina3
      name: 0f52390b-c781-43ae-bd62-553c77fa4cf7
      data: 2 # a flag enabling authentication only for LDAP plugin
      type: dword

  - debug: msg={{nGinaPassword}}

  - name: Configure pGina LDAP plugin
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\pGina3\Plugins\0f52390b-c781-43ae-bd62-553c77fa4cf7
      name: "{{ item.name }}"
      data: "{{ item.data }}"
      type: "{{ item.type }}"
    with_items:
      - name: DoSearch
        data: "True"
        type: string
      - name: LdapHost
        data: "192.168.0.201"
        type: multistring
      - name: LdapPort
        data: "636"
        type: dword
      - name: UseSsl
        data: "True"
        type: string
      - name: SearchContexts
        data: "dc=itsm,dc=local"
        type: multistring
      - name: SearchDN
        data: "cn=admin,dc=itsm,dc=local"
        type: string
      - name: SearchFilter
        data: "uid=%u"
        type: string
      - name: SearchPW
        data: "{{ nGinaPassword.output[0] }}"
        type: string
      