---
- hosts: all
  become: yes

  pre_tasks:
  - name: Update apt cache if needed.
    apt: 
      update_cache: yes
      cache_valid_time: 3600

  tasks:

  - name: Ensure dependency packages are installed.
    apt:
      name:
        - python3
        - python3-pip
        - python3-setuptools

        - debconf-utils
        - ldap-utils

        - libsasl2-dev
        - libldap2-dev
        - libssl-dev
      state: present

  - name: Ensure pip dependencies are installed.
    pip:
      name: python-ldap

  - name: Check debconf for slapd entries
    shell: (debconf-get-selections | grep -q -s slapd); echo $?
    register: slapd_debconf
    ignore_errors: yes
    changed_when: false

  - name: Setup unattended installation parameters for OpenLDAP installation.
    debconf:
      name: slapd
      question: "{{ item.key }}"
      vtype: "{{ item.type }}"
      value: "{{ item.value }}"
    with_items:
      - key: slapd/password1
        type: password
        value: password
      - key: slapd/password2
        type: password
        value: password
      - key: slapd/move_old_database
        type: boolean
        value: "true"
      - key: slapd/domain
        type: string
        value: itsm.local
      - key: shared/organization
        type: string
        value: ITSM
      - key: slapd/no_configuration
        type: boolean
        value: "false"
      - key: slapd/purge_database
        type: boolean
        value: "false"
      - key: slapd/allow_ldap_v2
        type: boolean
        value: "false"
      - key: slapd/backend
        type: select
        value: "MDB"
    when: "slapd_debconf.stdout.find('0') == -1"

  - name: Install OpenLDAP.
    apt:
      name: slapd
      state: present

  - name: Start OpenLDAP daemon.
    service: 
      name: slapd
      state: started
      enabled: yes

  - name: Configure Directory 1 to itsm.local.
    community.general.ldap_attrs:
      dn: olcDatabase={1}mdb,cn=config
      attributes:
          olcSuffix: dc=itsm,dc=local
      state: exact