Vagrant.configure("2") do |config|
  config.vm.define "ldapServer" do |ldapServer|
    ldapServer.vm.box = "ubuntu/focal64"
    ldapServer.vm.network "public_network", ip: "192.168.0.201", bridge: "enp0s31f6"
    ldapServer.vm.provision "ansible" do |ldapServerAnsible|
      ldapServerAnsible.playbook = "ldapServer.yml"
    end
  end
  config.vm.define "ldapUbuntuClient" do |ldapUbuntuClient|
    ldapUbuntuClient.vm.box = "ubuntu/focal64"
    ldapUbuntuClient.vm.network "public_network", ip: "192.168.0.202", bridge: "enp0s31f6"
    ldapUbuntuClient.vm.provision "ansible" do |ldapUbuntuClientAnsible|
      ldapUbuntuClientAnsible.playbook = "ldapClient.yml"
    end
  end
end

